version: '3'
services:
  ppt:
    tty: true
    build: .
    volumes:
      - ./files:/app/
    cap_add:
      - SYS_ADMIN

# Running Puppeteer in Docker
#   https://github.com/puppeteer/puppeteer/blob/a22aa5deac9fea29433908d49018105297524299/docs/troubleshooting.md#running-puppeteer-in-docker